language: elixir
elixir:
  - 1.2.1
otp_release:
  - 18.2
sudo: false
script:
  - mix test
  - mix dialyzer.plt
  - mix dialyzer --halt-exit-status
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
cache:
  directories:
    - .dialyzer
